
const cfg=window.TPG_CONFIG;
const $=s=>document.querySelector(s);
let client=null, categories=[], menuItems=[], bookings=[], selectedFile=null;
let calendarDate=new Date(), selectedDate=null;

function configured(){return cfg.SUPABASE_URL.startsWith("https://")&&!cfg.SUPABASE_ANON_KEY.includes("PASTE_")}
function placeholder(label="Menu"){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800"><rect width="100%" height="100%" fill="#173e2a"/><text x="50%" y="49%" text-anchor="middle" fill="white" font-family="Arial" font-size="34" font-weight="700">${String(label).replace(/[<>&"]/g,"")}</text><text x="50%" y="57%" text-anchor="middle" fill="#d8ad56" font-family="Arial" font-size="18">Image coming soon</text></svg>`)}

if(configured()){client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);$("#connectionInfo").textContent="เชื่อมต่อ Supabase configuration แล้ว"}
else{$("#loginStatus").textContent="กรุณาใส่ Publishable Key ใน config.js";$("#connectionInfo").textContent="ยังไม่ได้ใส่ Publishable Key"}

async function checkSession(){if(!client)return;const {data}=await client.auth.getSession();if(data.session)showDashboard(data.session.user)}
$("#loginButton").onclick=async()=>{if(!client)return;$("#loginStatus").textContent="กำลังเข้าสู่ระบบ...";const {data,error}=await client.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error)$("#loginStatus").textContent=error.message;else showDashboard(data.user)}
async function showDashboard(user){$("#loginPanel").hidden=true;$("#dashboard").hidden=false;$("#logoutButton").hidden=false;$("#adminUser").textContent=user.email||"Admin";await Promise.all([loadCategories(),loadMenus(),loadBookings()])}
$("#logoutButton").onclick=async()=>{await client.auth.signOut();location.reload()}

document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${b.dataset.tab}`));if(b.dataset.tab==="calendar")renderCalendar()})

async function loadCategories(){const {data,error}=await client.from("categories").select("*").order("sort_order");if(error)return alert(error.message);categories=data||[];$("#itemCategory").innerHTML="";$("#adminCategory").innerHTML='<option value="all">ทุกหมวด</option>';categories.forEach(c=>{$("#itemCategory").insertAdjacentHTML("beforeend",`<option value="${c.id}">${c.name_lo}</option>`);$("#adminCategory").insertAdjacentHTML("beforeend",`<option value="${c.id}">${c.name_lo}</option>`)})}
async function loadMenus(){const {data,error}=await client.from("menu_items").select("*,categories(name_lo)").order("sort_order");if(error)return alert(error.message);menuItems=data||[];renderMenus();updateStats()}
function filteredMenus(){const q=$("#adminSearch").value.trim().toLowerCase(),cat=$("#adminCategory").value,state=$("#adminAvailability").value;return menuItems.filter(i=>{const matchCat=cat==="all"||i.category_id===cat;const matchText=`${i.name_lo||""} ${i.name_th||""} ${i.name_en||""}`.toLowerCase().includes(q);const matchState=state==="all"||(state==="available"&&i.available)||(state==="unavailable"&&!i.available)||(state==="featured"&&i.featured);return matchCat&&matchText&&matchState})}
function renderMenus(){$("#adminMenuGrid").innerHTML="";filteredMenus().forEach(item=>{const card=document.createElement("article");card.className="admin-card";card.innerHTML=`<img alt="${item.name_lo}"><div class="admin-card-body"><h3>${item.name_lo}</h3><p>${item.categories?.name_lo||""} • ${Number(item.price).toLocaleString()} ກີບ</p><span class="availability ${item.available?"":"unavailable"}">${item.available?"มีขาย":"ปิดขาย"}</span> ${item.featured?'<span class="availability featured">แนะนำ</span>':""}<div class="admin-card-actions"><button class="edit">Edit</button><button class="delete">Delete</button></div></div>`;const img=card.querySelector("img");img.onerror=()=>{img.onerror=null;img.src=placeholder(item.name_lo)};img.src=item.image_url||placeholder(item.name_lo);card.querySelector(".edit").onclick=()=>startEdit(item);card.querySelector(".delete").onclick=()=>removeItem(item);$("#adminMenuGrid").appendChild(card)})}
function startEdit(i){$("#editId").value=i.id;$("#formTitle").textContent="แก้ไขเมนู";$("#itemNameLo").value=i.name_lo||"";$("#itemNameTh").value=i.name_th||"";$("#itemNameEn").value=i.name_en||"";$("#itemCategory").value=i.category_id;$("#itemPrice").value=i.price;$("#itemOrder").value=i.sort_order||999;$("#itemVariants").value=(i.variants||[]).join(" / ");$("#itemAvailable").checked=i.available;$("#itemFeatured").checked=i.featured;selectedFile=null;$("#imagePreview").hidden=!i.image_url;if(i.image_url)$("#imagePreview").src=i.image_url;window.scrollTo({top:0,behavior:"smooth"})}
function resetForm(){$("#menuForm").reset();$("#editId").value="";$("#formTitle").textContent="เพิ่มเมนูใหม่";$("#itemPrice").value=1000;$("#itemOrder").value=999;$("#itemAvailable").checked=true;selectedFile=null;$("#imagePreview").hidden=true}
$("#cancelEdit").onclick=resetForm;

const dz=$("#dropZone"),fileInput=$("#itemImage");
dz.onclick=()=>fileInput.click();
["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("dragover")}));
["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("dragover")}));
dz.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
fileInput.onchange=e=>handleFile(e.target.files[0]);
function handleFile(file){if(!file)return;if(file.size>5*1024*1024)return alert("ไฟล์ต้องไม่เกิน 5 MB");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return alert("รองรับ JPG, PNG และ WEBP");selectedFile=file;$("#imagePreview").src=URL.createObjectURL(file);$("#imagePreview").hidden=false}
async function uploadImage(file,itemId){if(!file)return null;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`menus/${itemId}-${Date.now()}.${ext}`;const {error}=await client.storage.from(cfg.STORAGE_BUCKET).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return {url:client.storage.from(cfg.STORAGE_BUCKET).getPublicUrl(path).data.publicUrl,path}}

$("#menuForm").onsubmit=async e=>{e.preventDefault();const editId=$("#editId").value,id=editId||crypto.randomUUID();const payload={name_lo:$("#itemNameLo").value.trim(),name_th:$("#itemNameTh").value.trim()||null,name_en:$("#itemNameEn").value.trim()||null,category_id:$("#itemCategory").value,price:Number($("#itemPrice").value),sort_order:Number($("#itemOrder").value),variants:$("#itemVariants").value.split("/").map(x=>x.trim()).filter(Boolean),available:$("#itemAvailable").checked,featured:$("#itemFeatured").checked};try{const image=await uploadImage(selectedFile,id);if(image){payload.image_url=image.url;payload.image_path=image.path}const query=editId?client.from("menu_items").update(payload).eq("id",editId):client.from("menu_items").insert({...payload,id});const {error}=await query;if(error)throw error;resetForm();await loadMenus();alert("บันทึกสำเร็จ")}catch(err){alert(err.message)}}
async function removeItem(item){if(!confirm(`ลบ ${item.name_lo}?`))return;const {error}=await client.from("menu_items").delete().eq("id",item.id);if(error)alert(error.message);else loadMenus()}
$("#adminSearch").oninput=renderMenus;$("#adminCategory").onchange=renderMenus;$("#adminAvailability").onchange=renderMenus;$("#refreshMenus").onclick=loadMenus;

async function loadBookings(){const {data,error}=await client.from("reservations").select("*").order("booking_date").order("booking_time");if(error)return console.error(error);bookings=data||[];renderBookings();renderCalendar();updateStats()}
function renderBookings(){const q=$("#bookingSearch").value.trim().toLowerCase();$("#bookingRows").innerHTML="";bookings.filter(b=>`${b.customer_name} ${b.phone}`.toLowerCase().includes(q)).forEach(b=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${b.booking_date}</td><td>${b.booking_time}</td><td>${b.customer_name}</td><td>${b.phone}</td><td>${b.guest_count}</td><td>${b.note||""}</td><td><select><option ${b.status==="new"?"selected":""}>new</option><option ${b.status==="confirmed"?"selected":""}>confirmed</option><option ${b.status==="cancelled"?"selected":""}>cancelled</option><option ${b.status==="completed"?"selected":""}>completed</option><option ${b.status==="no_show"?"selected":""}>no_show</option></select></td>`;tr.querySelector("select").onchange=async e=>{await client.from("reservations").update({status:e.target.value}).eq("id",b.id);loadBookings()};$("#bookingRows").appendChild(tr)})}
$("#bookingSearch").oninput=renderBookings;$("#refreshBookings").onclick=loadBookings;

function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth();$("#calendarTitle").textContent=new Intl.DateTimeFormat("th-TH",{month:"long",year:"numeric"}).format(calendarDate);const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());$("#calendarGrid").innerHTML="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),dayBookings=bookings.filter(b=>b.booking_date===key);const cell=document.createElement("div");cell.className=`calendar-day ${d.getMonth()!==month?"muted":""} ${selectedDate===key?"selected":""}`;cell.innerHTML=`<strong>${d.getDate()}</strong>${dayBookings.length?`<span class="booking-dot">${dayBookings.length} การจอง</span>`:""}`;cell.onclick=()=>{selectedDate=key;renderCalendar();renderDayBookings(key)};$("#calendarGrid").appendChild(cell)}}
function renderDayBookings(key){const list=bookings.filter(b=>b.booking_date===key);$("#dayBookings").innerHTML=`<h3>การจองวันที่ ${key}</h3>`+(list.length?list.map(b=>`<div class="day-booking"><strong>${b.booking_time} • ${b.customer_name}</strong><div>${b.guest_count} คน • ${b.phone} • ${b.status}</div><small>${b.note||""}</small></div>`).join(""):"<p>ยังไม่มีการจอง</p>")}
$("#prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};

function updateStats(){$("#statMenu").textContent=menuItems.length;$("#statAvailable").textContent=menuItems.filter(i=>i.available).length;$("#statFeatured").textContent=menuItems.filter(i=>i.featured).length;$("#statBookings").textContent=bookings.length}
checkSession();
