window.TPG_SEED_MENU = [
  {
    "id": 1,
    "category": "ຕຳ",
    "name": "ຕຳປູມ້າ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 1,
    "featured": false
  },
  {
    "id": 2,
    "category": "ຕຳ",
    "name": "ຕຳກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 2,
    "featured": false
  },
  {
    "id": 3,
    "category": "ຕຳ",
    "name": "ຕຳຫອຍແຄງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 3,
    "featured": false
  },
  {
    "id": 4,
    "category": "ຕຳ",
    "name": "ຕຳປາມຶກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 4,
    "featured": false
  },
  {
    "id": 5,
    "category": "ຕຳ",
    "name": "ຕຳປູ+ກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 5,
    "featured": false
  },
  {
    "id": 6,
    "category": "ຕຳ",
    "name": "ຕຳປູ+ຫອຍແຄງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 6,
    "featured": false
  },
  {
    "id": 7,
    "category": "ຕຳ",
    "name": "ຕຳທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 7,
    "featured": false
  },
  {
    "id": 8,
    "category": "ຕຳ",
    "name": "ຕຳແຊວມ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 8,
    "featured": false
  },
  {
    "id": 9,
    "category": "ຕຳ",
    "name": "ຕຳກຸ້ງ+ແຊວມ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 9,
    "featured": false
  },
  {
    "id": 10,
    "category": "ຕຳ",
    "name": "ຕຳຕ່ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 10,
    "featured": false
  },
  {
    "id": 11,
    "category": "ຕຳ",
    "name": "ຕຳຕີນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 11,
    "featured": false
  },
  {
    "id": 12,
    "category": "ຕຳ",
    "name": "ຕຳຍໍ່ບັ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 12,
    "featured": false
  },
  {
    "id": 13,
    "category": "ຕຳ",
    "name": "ຕຳປ່າ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 13,
    "featured": false
  },
  {
    "id": 14,
    "category": "ຕຳ",
    "name": "ຕຳເສັ້ນແກ້ວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 14,
    "featured": false
  },
  {
    "id": 15,
    "category": "ຕຳ",
    "name": "ຕຳເຂົ້າປຽກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 15,
    "featured": false
  },
  {
    "id": 16,
    "category": "ຕຳ",
    "name": "ຕຳໝີ່ຂາວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 16,
    "featured": false
  },
  {
    "id": 17,
    "category": "ຕຳ",
    "name": "ຕຳໝີ່ໄວໆ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 17,
    "featured": false
  },
  {
    "id": 18,
    "category": "ຕຳ",
    "name": "ຕຳເສັ້ນລ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 18,
    "featured": false
  },
  {
    "id": 19,
    "category": "ຕຳ",
    "name": "ຕຳໝາກຮຸ່ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 19,
    "featured": false
  },
  {
    "id": 20,
    "category": "ຕຳ",
    "name": "ຕຳແຕງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 20,
    "featured": false
  },
  {
    "id": 21,
    "category": "ຕຳ",
    "name": "ຕຳເຂົ້າປຸ້ນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 21,
    "featured": false
  },
  {
    "id": 22,
    "category": "ຕຳ",
    "name": "ຕຳສາລີໄຂ່ເຄັມ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 22,
    "featured": false
  },
  {
    "id": 23,
    "category": "ຕຳ",
    "name": "ຕຳຖາດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 23,
    "featured": false
  },
  {
    "id": 24,
    "category": "ຕຳ",
    "name": "ຕຳຖົ່ວໝູກ໋ອບ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 24,
    "featured": false
  },
  {
    "id": 25,
    "category": "ຍຳ",
    "name": "ສະລັດລາວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 25,
    "featured": false
  },
  {
    "id": 26,
    "category": "ຍຳ",
    "name": "ຍຳຍໍ່ບັ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 26,
    "featured": false
  },
  {
    "id": 27,
    "category": "ຍຳ",
    "name": "ຍຳໄຂ່ຍ່ຽວມ້າ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 27,
    "featured": false
  },
  {
    "id": 28,
    "category": "ຍຳ",
    "name": "ຍຳຫອຍແຄງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 28,
    "featured": false
  },
  {
    "id": 29,
    "category": "ຍຳ",
    "name": "ຍຳກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 29,
    "featured": false
  },
  {
    "id": 30,
    "category": "ຍຳ",
    "name": "ຍຳທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 30,
    "featured": false
  },
  {
    "id": 31,
    "category": "ຍຳ",
    "name": "ຍຳປູອັດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 31,
    "featured": false
  },
  {
    "id": 32,
    "category": "ຍຳ",
    "name": "ຍຳເລັບມື້ນາງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 32,
    "featured": false
  },
  {
    "id": 33,
    "category": "ຍຳ",
    "name": "ຍຳໃສ້ອ່ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 33,
    "featured": false
  },
  {
    "id": 34,
    "category": "ຍຳ",
    "name": "ຍຳປູມ້າ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 34,
    "featured": false
  },
  {
    "id": 35,
    "category": "ຍຳ",
    "name": "ຍຳແຊວມ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 35,
    "featured": false
  },
  {
    "id": 36,
    "category": "ຍຳ",
    "name": "ຍຳໄວໆ+ສົ້ມໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 36,
    "featured": false
  },
  {
    "id": 37,
    "category": "ຍຳ",
    "name": "ຍຳໂຕ່ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 37,
    "featured": false
  },
  {
    "id": 38,
    "category": "ຍຳ",
    "name": "ຍຳງົວເຜົາ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 38,
    "featured": false
  },
  {
    "id": 39,
    "category": "ຍຳ",
    "name": "ຍຳເສັ້ນລ້ອນ+ໝູສັບ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 39,
    "featured": false
  },
  {
    "id": 40,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມເລືອດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 40,
    "featured": false
  },
  {
    "id": 41,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມແຊບ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 41,
    "featured": false
  },
  {
    "id": 42,
    "category": "ຕົ້ມ",
    "name": "ແກງໜໍ່",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 42,
    "featured": false
  },
  {
    "id": 43,
    "category": "ຕົ້ມ",
    "name": "ແກງເຫັດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 43,
    "featured": false
  },
  {
    "id": 44,
    "category": "ຕົ້ມ",
    "name": "ແກງຈືດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 44,
    "featured": false
  },
  {
    "id": 45,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມແຊບດູກຂ້າງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 45,
    "featured": false
  },
  {
    "id": 46,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມຍຳຫົວແຊວມ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 46,
    "featured": false
  },
  {
    "id": 47,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມຍຳທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 47,
    "featured": false
  },
  {
    "id": 48,
    "category": "ຕົ້ມ",
    "name": "ຕົ້ມຍຳປາເຄິງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 48,
    "featured": false
  },
  {
    "id": 49,
    "category": "ທອດ",
    "name": "ທອດລູກຊີ້ນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 49,
    "featured": false
  },
  {
    "id": 50,
    "category": "ທອດ",
    "name": "ທອດຫົວກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 50,
    "featured": false
  },
  {
    "id": 51,
    "category": "ທອດ",
    "name": "ທອດເຫືອກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 51,
    "featured": false
  },
  {
    "id": 52,
    "category": "ທອດ",
    "name": "ທອດຄາງເປັດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 52,
    "featured": false
  },
  {
    "id": 53,
    "category": "ທອດ",
    "name": "ທອດນ໋ອງໄກ່",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 53,
    "featured": false
  },
  {
    "id": 54,
    "category": "ທອດ",
    "name": "ກຸ້ງຊຸບແປ້ງທອດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 54,
    "featured": false
  },
  {
    "id": 55,
    "category": "ທອດ",
    "name": "ທອດດູກຂ້າງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 55,
    "featured": false
  },
  {
    "id": 56,
    "category": "ທອດ",
    "name": "ທອດຮ໋ອນດ໋ອກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 56,
    "featured": false
  },
  {
    "id": 57,
    "category": "ທອດ",
    "name": "ທອດມັນຝຣັ່ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 57,
    "featured": false
  },
  {
    "id": 58,
    "category": "ທອດ",
    "name": "ທອດປາມຶກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 58,
    "featured": false
  },
  {
    "id": 59,
    "category": "ທອດ",
    "name": "ເຫັດຊຸບແປ້ງທອດ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 59,
    "featured": false
  },
  {
    "id": 60,
    "category": "ທອດ",
    "name": "ທອດໄສ້ອ່ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 60,
    "featured": false
  },
  {
    "id": 61,
    "category": "ທອດ",
    "name": "ທອດເອັນເຫຼືອງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 61,
    "featured": false
  },
  {
    "id": 62,
    "category": "ທອດ",
    "name": "ທອດໄສ້ກອກອີ່ສານ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 62,
    "featured": false
  },
  {
    "id": 63,
    "category": "ຕາມສັ່ງ",
    "name": "ກຸ້ງແຊ່ນໍ້າປາ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 63,
    "featured": false
  },
  {
    "id": 64,
    "category": "ຕາມສັ່ງ",
    "name": "ສົ້ມໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 64,
    "featured": false
  },
  {
    "id": 65,
    "category": "ຕາມສັ່ງ",
    "name": "ປາໜຶ້ງໝາກນາວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 65,
    "featured": false
  },
  {
    "id": 66,
    "category": "ຕາມສັ່ງ",
    "name": "ປາລາດພິກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 66,
    "featured": false
  },
  {
    "id": 67,
    "category": "ຕາມສັ່ງ",
    "name": "ປານິນທອດສະໝູນໄພ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 67,
    "featured": false
  },
  {
    "id": 68,
    "category": "ຕາມສັ່ງ",
    "name": "ປາຊາບະລົມຄວັນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 68,
    "featured": false
  },
  {
    "id": 69,
    "category": "ຕາມສັ່ງ",
    "name": "ປາປ້ຽວຫວານ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 69,
    "featured": false
  },
  {
    "id": 70,
    "category": "ຕາມສັ່ງ",
    "name": "ກ້ອຍປານິນ+ຕົ້ມ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 70,
    "featured": false
  },
  {
    "id": 71,
    "category": "ຕາມສັ່ງ",
    "name": "ກ້ອຍປາເຄິ່ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 71,
    "featured": false
  },
  {
    "id": 72,
    "category": "ຕາມສັ່ງ",
    "name": "ຕົ້ມສົ້ມປາເຄິງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 72,
    "featured": false
  },
  {
    "id": 73,
    "category": "ຕາມສັ່ງ",
    "name": "ກ້ອຍແຊວມ້ອນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 73,
    "featured": false
  },
  {
    "id": 74,
    "category": "ຕາມສັ່ງ",
    "name": "ປູອັດບາຊາບິ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 74,
    "featured": false
  },
  {
    "id": 75,
    "category": "ຕາມສັ່ງ",
    "name": "ແຊວມ້ອນບາຊາບິ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 75,
    "featured": false
  },
  {
    "id": 76,
    "category": "ຕາມສັ່ງ",
    "name": "ລວກຊີ້ນງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 76,
    "featured": false
  },
  {
    "id": 77,
    "category": "ຕາມສັ່ງ",
    "name": "ລວກທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 77,
    "featured": false
  },
  {
    "id": 78,
    "category": "ຕາມສັ່ງ",
    "name": "ລາບງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 78,
    "featured": false
  },
  {
    "id": 79,
    "category": "ຕາມສັ່ງ",
    "name": "ພັນໝ້ຽງປາ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 79,
    "featured": false
  },
  {
    "id": 80,
    "category": "ຕາມສັ່ງ",
    "name": "ເອາະຊີ້ນໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 80,
    "featured": false
  },
  {
    "id": 81,
    "category": "ຕາມສັ່ງ",
    "name": "ເອາະຊີ້ນງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 81,
    "featured": false
  },
  {
    "id": 82,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັກບົ້ງໄຟແດງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 82,
    "featured": false
  },
  {
    "id": 83,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັກກາດນາໝູກອບ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 83,
    "featured": false
  },
  {
    "id": 84,
    "category": "ຕາມສັ່ງ",
    "name": "ກະເພົາໝູກອບ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 84,
    "featured": false
  },
  {
    "id": 85,
    "category": "ຕາມສັ່ງ",
    "name": "ຂົ້ວເຫັດລວມ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 85,
    "featured": false
  },
  {
    "id": 86,
    "category": "ຕາມສັ່ງ",
    "name": "ຂົ້ວຜັກລວມ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 86,
    "featured": false
  },
  {
    "id": 87,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັດຫອຍແຄງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 87,
    "featured": false
  },
  {
    "id": 88,
    "category": "ຕາມສັ່ງ",
    "name": "ສະເຕັກງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 88,
    "featured": false
  },
  {
    "id": 89,
    "category": "ຕາມສັ່ງ",
    "name": "ສະເຕັກໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 89,
    "featured": false
  },
  {
    "id": 90,
    "category": "ຕາມສັ່ງ",
    "name": "ຂົ້ວເຫັດເຂັມໃສ່ກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 90,
    "featured": false
  },
  {
    "id": 91,
    "category": "ຕາມສັ່ງ",
    "name": "ປາມຶກຜັດໄຂ່ເຂັມ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 91,
    "featured": false
  },
  {
    "id": 92,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັດເສື້ອຮ້ອງໄຫ້",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 92,
    "featured": false
  },
  {
    "id": 93,
    "category": "ຕາມສັ່ງ",
    "name": "ກະເຜົາໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 93,
    "featured": false
  },
  {
    "id": 94,
    "category": "ຕາມສັ່ງ",
    "name": "ກະເຜົາທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 94,
    "featured": false
  },
  {
    "id": 95,
    "category": "ຕາມສັ່ງ",
    "name": "ແລັມໂບ້ໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 95,
    "featured": false
  },
  {
    "id": 96,
    "category": "ຕາມສັ່ງ",
    "name": "ແລັມໂບ້ງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 96,
    "featured": false
  },
  {
    "id": 97,
    "category": "ຕາມສັ່ງ",
    "name": "ແລັມໂບ້ອ່ຽນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 97,
    "featured": false
  },
  {
    "id": 98,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັດຂີ້ເມົາໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 98,
    "featured": false
  },
  {
    "id": 99,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັດຂີ້ເມົາງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 99,
    "featured": false
  },
  {
    "id": 100,
    "category": "ຕາມສັ່ງ",
    "name": "ຜັດຂີ້ເມົາທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 100,
    "featured": false
  },
  {
    "id": 101,
    "category": "ປີ້ງ",
    "name": "ປີ້ງຄໍໝູຍ້າງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 101,
    "featured": false
  },
  {
    "id": 102,
    "category": "ປີ້ງ",
    "name": "ປີ້ງປາ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 102,
    "featured": false
  },
  {
    "id": 103,
    "category": "ປີ້ງ",
    "name": "ປິ້ງຊີ້ນງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 103,
    "featured": false
  },
  {
    "id": 104,
    "category": "ປີ້ງ",
    "name": "ປີ້ງກຸ້ງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 104,
    "featured": false
  },
  {
    "id": 105,
    "category": "ປີ້ງ",
    "name": "ປີ້ງປາມຶກ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 105,
    "featured": false
  },
  {
    "id": 106,
    "category": "ປີ້ງ",
    "name": "ປີ້ງເສື້ອຮ້ອງໄຫ້",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 106,
    "featured": false
  },
  {
    "id": 107,
    "category": "ຜັດ",
    "name": "ເຂົ້າຈ້າວ",
    "variants": [
      "ຈານ",
      "ໝໍ້"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 107,
    "featured": false
  },
  {
    "id": 108,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດໝູ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 108,
    "featured": false
  },
  {
    "id": 109,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດງົວ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 109,
    "featured": false
  },
  {
    "id": 110,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດທະເລ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 110,
    "featured": false
  },
  {
    "id": 111,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດໝູກອບ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 111,
    "featured": false
  },
  {
    "id": 112,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດຕົ້ມຍຳ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 112,
    "featured": false
  },
  {
    "id": 113,
    "category": "ຜັດ",
    "name": "ເຂົ້າຜັດໃສ້ກອກ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 113,
    "featured": false
  },
  {
    "id": 114,
    "category": "ຜັດ",
    "name": "ເຂົ້າໝູທອດກະທຽມ",
    "variants": [
      "ຈານນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 114,
    "featured": false
  },
  {
    "id": 115,
    "category": "ຜັດ",
    "name": "ເຂົ້າຄຸກກະປິ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 115,
    "featured": false
  },
  {
    "id": 116,
    "category": "ຜັດ",
    "name": "ຜັດໄທໝູ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 116,
    "featured": false
  },
  {
    "id": 117,
    "category": "ຜັດ",
    "name": "ຜັດໄທງົວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 117,
    "featured": false
  },
  {
    "id": 118,
    "category": "ຜັດ",
    "name": "ຜັດໄທທະເລ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 118,
    "featured": false
  },
  {
    "id": 119,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ນໍ້າດື່ມກາງ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 119,
    "featured": false
  },
  {
    "id": 120,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ແປັບຊີຕຸກໃຫຍ່",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 120,
    "featured": false
  },
  {
    "id": 121,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ແປັບຊີແກ້ວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 121,
    "featured": false
  },
  {
    "id": 122,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ເບຍລາວ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 122,
    "featured": false
  },
  {
    "id": 123,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ເບຍໄຮນິເກັນ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 123,
    "featured": false
  },
  {
    "id": 124,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ຊຳເມີບີ",
    "variants": [],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 124,
    "featured": false
  },
  {
    "id": 125,
    "category": "ເຄື່ອງດື່ມ",
    "name": "ນໍ້າກ້ອນ",
    "variants": [
      "ໂຖນ້ອຍ",
      "ໃຫຍ່"
    ],
    "price": 1000,
    "image": "logo.png",
    "available": true,
    "image_url": "",
    "sort_order": 125,
    "featured": false
  }
];
